<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Aravindh-PC" failures="2" tests="15" name="Testng Test" time="1.207" errors="0" timestamp="04 Apr 2019 01:57:08 GMT">
  <testcase classname="com.testng.ExceptionTimeouttest" name="infiniteloop" time="1.016">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.ExceptionTimeouttest.infiniteloop() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.ExceptionTimeouttest.infiniteloop() didn't finish within the time-out 1000
at java.base@11.0.2/java.io.FileOutputStream.writeBytes(Native Method)
at java.base@11.0.2/java.io.FileOutputStream.write(FileOutputStream.java:354)
at java.base@11.0.2/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
at java.base@11.0.2/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
at java.base@11.0.2/java.io.PrintStream.write(PrintStream.java:561)
at java.base@11.0.2/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
at java.base@11.0.2/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
at java.base@11.0.2/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
at java.base@11.0.2/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:184)
at java.base@11.0.2/java.io.PrintStream.write(PrintStream.java:606)
at java.base@11.0.2/java.io.PrintStream.print(PrintStream.java:676)
at java.base@11.0.2/java.io.PrintStream.println(PrintStream.java:812)
at app//com.testng.ExceptionTimeouttest.infiniteloop(ExceptionTimeouttest.java:12)
at java.base@11.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@11.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.2/java.lang.Thread.run(Thread.java:834)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- infiniteloop -->
  <testcase classname="com.testng.ExceptionTimeouttest" name="test1" time="0.004"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.006"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.002"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.001"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.003"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.002"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.001"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.002"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.008"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.009"/>
  <testcase classname="com.testng.InvocationCountTest" name="sum" time="0.012"/>
  <testcase classname="com.testng.TestngBasics" name="googlelogotest" time="0.007"/>
  <testcase classname="com.testng.TestngBasics" name="googletitletest" time="0.008"/>
  <testcase classname="com.testng.TestngFeatures" name="login" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.testng.TestngFeatures.login(TestngFeatures.java:10)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="com.testng.TestngBasics" name="searchTest" time="0.0">
    <ignored/>
  </testcase> <!-- searchTest -->
</testsuite> <!-- Testng Test -->
