<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Aravindh-PC" failures="0" tests="2" name="com.testng.ExceptionTimeouttest" time="1.020" errors="1" timestamp="04 Apr 2019 01:57:08 GMT" skipped="0">
  <testcase classname="com.testng.ExceptionTimeouttest" name="infiniteloop" time="1.016">
    <error message="Method com.testng.ExceptionTimeouttest.infiniteloop() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.ExceptionTimeouttest.infiniteloop() didn't finish within the time-out 1000
at java.base@11.0.2/java.io.FileOutputStream.writeBytes(Native Method)
at java.base@11.0.2/java.io.FileOutputStream.write(FileOutputStream.java:354)
at java.base@11.0.2/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
at java.base@11.0.2/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
at java.base@11.0.2/java.io.PrintStream.write(PrintStream.java:561)
at java.base@11.0.2/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
at java.base@11.0.2/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
at java.base@11.0.2/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
at java.base@11.0.2/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:184)
at java.base@11.0.2/java.io.PrintStream.write(PrintStream.java:606)
at java.base@11.0.2/java.io.PrintStream.print(PrintStream.java:676)
at java.base@11.0.2/java.io.PrintStream.println(PrintStream.java:812)
at app//com.testng.ExceptionTimeouttest.infiniteloop(ExceptionTimeouttest.java:12)
at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@11.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@11.0.2/java.lang.reflect.Method.invoke(Method.java:566)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)
at java.base@11.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@11.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.2/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- infiniteloop -->
  <testcase classname="com.testng.ExceptionTimeouttest" name="test1" time="0.004"/>
</testsuite> <!-- com.testng.ExceptionTimeouttest -->
